window.GLOBAL_SETUP = "\nclass Link:\n    \"\"\"FA26-style linked list. Empty is (). Link.empty aliases () so old\n    solutions that say Link.empty or `is Link.empty` still run.\"\"\"\n    empty = ()\n    def __init__(self, first, rest=()):\n        assert rest == () or isinstance(rest, Link), \"rest must be a Link or ()\"\n        self.first = first\n        self.rest = rest\n    def __repr__(self):\n        if self.rest == ():\n            return \"Link(\" + repr(self.first) + \")\"\n        return \"Link(\" + repr(self.first) + \", \" + repr(self.rest) + \")\"\n    def __str__(self):\n        s, out = self, \"(\"\n        while isinstance(s, Link):\n            out += str(s.first) + \" \"\n            s = s.rest\n        return out.rstrip(\" \") + \")\"\n\ndef make_link(seq):\n    r = ()\n    for x in reversed(list(seq)):\n        r = Link(x, r)\n    return r\n\ndef to_list(link):\n    out = []\n    while isinstance(link, Link):\n        out.append(link.first)\n        link = link.rest\n    return out\n\nimport contextlib, io\ndef _caught_out(fn):\n    buf = io.StringIO()\n    with contextlib.redirect_stdout(buf):\n        fn()\n    return buf.getvalue()\n";
window.PROBLEMS = [
 {
  "id": "fa24_semiperfect",
  "title": "Almost a Perfect Question",
  "cat": "Recursion",
  "source": "Fall 2024 MT2, Q4(a)",
  "exam": "https://cs61a.org/resources/fa24/mt2/61a-fa24-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa24/mt2/61a-fa24-mt2_sol.pdf",
  "desc": "A number is semiperfect if some subset of its proper divisors (divisors less than n, each used at most once) sums to n. Return whether n is semiperfect.",
  "setup": "",
  "starter": "def semiperfect(n):\n    \"\"\"Return whether n equals the sum of some subset of its proper divisors.\n    >>> semiperfect(6)    # 1 + 2 + 3\n    True\n    >>> semiperfect(7)    # only proper divisor is 1\n    False\n    >>> semiperfect(28)   # 1 + 2 + 4 + 7 + 14\n    True\n    >>> [k for k in range(1, 40) if semiperfect(k)]\n    [6, 12, 18, 20, 24, 28, 30, 36]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def semiperfect(n):\n    divs = [d for d in range(1, n) if n % d == 0]\n    def f(s, i):\n        if s == 0:\n            return True\n        if s < 0 or i == len(divs):\n            return False\n        return f(s - divs[i], i + 1) or f(s, i + 1)\n    return f(n, 0)",
  "tests": "assert semiperfect(6) is True\nassert semiperfect(7) is False\nassert semiperfect(28) is True\nassert semiperfect(22) is False\nassert [k for k in range(1, 40) if semiperfect(k)] == [6, 12, 18, 20, 24, 28, 30, 36]"
 },
 {
  "id": "sp25_ways",
  "title": "Just Add and Multiply (ways)",
  "cat": "Recursion",
  "source": "Spring 2025 MT2, Q5(b)",
  "exam": "https://cs61a.org/resources/sp25/mt2/61a-sp25-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp25/mt2/61a-sp25-mt2_sol.pdf",
  "desc": "A plus-times expression inserts + or * between each adjacent pair of n numbers (n-1 gaps). Count the expressions in which no run of consecutive * is longer than k.",
  "setup": "",
  "starter": "def ways(k, n):\n    \"\"\"Count plus-times expressions for n numbers with no run of\n    consecutive * longer than k.\n    >>> ways(1, 4)\n    5\n    >>> ways(2, 4)\n    7\n    >>> ways(2, 5)\n    13\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def ways(k, n):\n    def f(gaps, run):\n        if gaps == 0:\n            return 1\n        total = f(gaps - 1, 0)          # place +\n        if run < k:\n            total += f(gaps - 1, run + 1)  # place *\n        return total\n    return f(n - 1, 0)",
  "tests": "assert ways(1, 4) == 5\nassert ways(2, 4) == 7\nassert ways(2, 5) == 13\nassert ways(1, 1) == 1\nassert ways(3, 4) == 8"
 },
 {
  "id": "sp25_close",
  "title": "Just Add and Multiply (close)",
  "cat": "Recursion",
  "source": "Spring 2025 MT2, Q5(c)",
  "exam": "https://cs61a.org/resources/sp25/mt2/61a-sp25-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp25/mt2/61a-sp25-mt2_sol.pdf",
  "desc": "A plus-times expression's value is a sum of products of contiguous groups of s (since * binds tighter than +). Return the achievable value closest in absolute distance to x. Empty list returns 0.",
  "setup": "def product(s):\n    p = 1\n    for x in s:\n        p *= x\n    return p",
  "starter": "def close(s, x):\n    \"\"\"Return the plus-times expression value for list s closest to x.\n    >>> close([1, 2, 3, 4], 10)   # 1 + 2 + 3 + 4\n    10\n    >>> close([1, 2, 3, 4], 20)   # 1 * 2 * 3 * 4\n    24\n    >>> close([3, 7, 5, 4, 2, 6], 66)  # 3*7 + 5*4*2 + 6\n    67\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def close(s, x):\n    def values(s):\n        if len(s) == 0:\n            return {0}\n        res = set()\n        for i in range(1, len(s) + 1):\n            head = product(s[:i])\n            if i == len(s):\n                res.add(head)\n            else:\n                for r in values(s[i:]):\n                    res.add(head + r)\n        return res\n    if len(s) == 0:\n        return 0\n    return min(values(s), key=lambda v: abs(v - x))",
  "tests": "assert close([1, 2, 3, 4], 10) == 10\nassert close([1, 2, 3, 4], 20) == 24\nassert close([3, 7, 5, 4, 2, 6], 66) == 67\nassert close([], 5) == 0\nassert close([5], 0) == 5"
 },
 {
  "id": "fa23_fit",
  "title": "A Perfect Question",
  "cat": "Recursion",
  "source": "Fall 2023 MT2, Q4(a)",
  "exam": "https://cs61a.org/resources/fa23/mt2/61a-fa23-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa23/mt2/61a-fa23-mt2_sol.pdf",
  "desc": "Return whether total can be written as a sum of exactly n positive perfect squares (1, 4, 9, 16, ...), repeats allowed.",
  "setup": "",
  "starter": "def fit(total, n):\n    \"\"\"Return whether total is a sum of exactly n positive perfect squares.\n    >>> fit(4, 1)    # 4 = 2*2\n    True\n    >>> fit(4, 2)    # cannot be two positive squares\n    False\n    >>> fit(12, 3)   # 4 + 4 + 4\n    True\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def fit(total, n):\n    def f(total, n, k):\n        if total == 0 and n == 0:\n            return True\n        if total <= 0 or n == 0 or k * k > total:\n            return False\n        return f(total - k * k, n - 1, k) or f(total, n, k + 1)\n    return f(total, n, 1)",
  "tests": "assert fit(4, 1) is True\nassert fit(4, 2) is False\nassert fit(12, 3) is True\nassert fit(1, 1) is True\nassert fit(2, 2) is True\nassert fit(3, 2) is False"
 },
 {
  "id": "sp23_count_park",
  "title": "Parking",
  "cat": "Recursion",
  "source": "Spring 2023 MT2, Q5(a)",
  "exam": "https://cs61a.org/resources/sp23/mt2/61a-sp23-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp23/mt2/61a-sp23-mt2_sol.pdf",
  "desc": "Count strings of length n made of '.' (empty, 1 spot), '%' (motorcycle, 1 spot), and '<>' (car, 2 spots).",
  "setup": "",
  "starter": "def count_park(n):\n    \"\"\"Count the ways to fill a row of n spots.\n    >>> count_park(1)   # '.'  '%'\n    2\n    >>> count_park(2)   # '..' '.%' '%.' '%%' '<>'\n    5\n    >>> count_park(4)\n    29\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def count_park(n):\n    if n < 0:\n        return 0\n    if n == 0:\n        return 1\n    return count_park(n - 1) + count_park(n - 1) + count_park(n - 2)",
  "tests": "assert count_park(1) == 2\nassert count_park(2) == 5\nassert count_park(3) == 12\nassert count_park(4) == 29\nassert count_park(0) == 1"
 },
 {
  "id": "fa22_count_subsets",
  "title": "Aim for 100",
  "cat": "Recursion",
  "source": "Fall 2022 MT2, Q5(a)",
  "exam": "https://cs61a.org/resources/fa22/mt2/61a-fa22-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa22/mt2/61a-fa22-mt2_sol.pdf",
  "desc": "Count the subsequences of list s (elements kept in order, each chosen or not) whose values sum to exactly 100.",
  "setup": "",
  "starter": "def count_subsets(s):\n    \"\"\"Count subsequences of s that sum to exactly 100.\n    >>> count_subsets([25, 50, 75, 100, 125, 150])  # [25, 75], [100]\n    2\n    >>> count_subsets([25, 50, 25, 75])             # three ways\n    3\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def count_subsets(s):\n    def helper(sum_so_far, index):\n        if sum_so_far == 100:\n            return 1\n        if index == len(s) or sum_so_far > 100:\n            return 0\n        return helper(sum_so_far + s[index], index + 1) + helper(sum_so_far, index + 1)\n    return helper(0, 0)",
  "tests": "assert count_subsets([25, 50, 75, 100, 125, 150]) == 2\nassert count_subsets([25, 50, 25, 75]) == 3\nassert count_subsets([]) == 0\nassert count_subsets([100]) == 1\nassert count_subsets([50, 50, 50]) == 3"
 },
 {
  "id": "fa19_switch",
  "title": "Best of Both",
  "cat": "Recursion",
  "source": "Fall 2019 MT2, Q6",
  "exam": "https://cs61a.org/resources/fa19/mt2/61a-fa19-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa19/mt2/61a-fa19-mt2_sol.pdf",
  "desc": "s and t are equal-length lists. A switch list takes each position from s or t. The switch count is how many times the source changes between consecutive positions, plus one if position 0 comes from t. Return the switch list with the largest sum whose switch count is at most k.",
  "setup": "",
  "starter": "def switch(s, t, k):\n    \"\"\"Return the max-sum switch list of s and t with at most k switches.\n    >>> switch([1, 2, 7], [3, 4, 5], 0)\n    [1, 2, 7]\n    >>> switch([1, 2, 7], [3, 4, 5], 1)\n    [3, 4, 5]\n    >>> switch([1, 2, 7], [3, 4, 5], 2)\n    [3, 4, 7]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def switch(s, t, k):\n    from itertools import product as _p\n    n = len(s)\n    best = None\n    for ch in _p([0, 1], repeat=n):\n        sw = (1 if n and ch[0] == 1 else 0)\n        for i in range(1, n):\n            if ch[i] != ch[i - 1]:\n                sw += 1\n        if sw <= k:\n            lst = [t[i] if ch[i] else s[i] for i in range(n)]\n            if best is None or sum(lst) > sum(best):\n                best = lst\n    return best if best is not None else list(s)",
  "tests": "assert switch([1, 2, 7], [3, 4, 5], 0) == [1, 2, 7]\nassert switch([1, 2, 7], [3, 4, 5], 1) == [3, 4, 5]\nassert switch([1, 2, 7], [3, 4, 5], 2) == [3, 4, 7]\nassert switch([5], [9], 0) == [5]\nassert switch([5], [9], 1) == [9]"
 },
 {
  "id": "fa18_plus",
  "title": "Nonplussed (plus)",
  "cat": "Recursion",
  "source": "Fall 2018 MT2, Q4(a)",
  "exam": "https://cs61a.org/resources/fa18/mt2/61a-fa18-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa18/mt2/61a-fa18-mt2_sol.pdf",
  "desc": "Insert + signs between the digits of n so that every term has one or two digits (a two-digit term starting with 0 is just its ones digit). Return the largest total achievable.",
  "setup": "",
  "starter": "def plus(n):\n    \"\"\"Largest sum from splitting n's digits into 1- or 2-digit terms.\n    >>> plus(123456)   # 12 + 34 + 56\n    102\n    >>> plus(1604)     # 1 + 60 + 4\n    65\n    >>> plus(160450)   # 1 + 60 + 4 + 50\n    115\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def plus(n):\n    s = str(n)\n    def go(s):\n        if s == \"\":\n            return 0\n        best = int(s[0]) + go(s[1:])\n        if len(s) >= 2:\n            best = max(best, int(s[:2]) + go(s[2:]))\n        return best\n    return go(s)",
  "tests": "assert plus(123456) == 102\nassert plus(1604) == 65\nassert plus(160450) == 115\nassert plus(0) == 0\nassert plus(5) == 5"
 },
 {
  "id": "fa18_plusses",
  "title": "Nonplussed (plusses)",
  "cat": "Recursion",
  "source": "Fall 2018 MT2, Q4(b)",
  "exam": "https://cs61a.org/resources/fa18/mt2/61a-fa18-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa18/mt2/61a-fa18-mt2_sol.pdf",
  "desc": "Using the same 1- or 2-digit term rule as plus, count how many distinct plus expressions for n have a value strictly less than cap.",
  "setup": "",
  "starter": "def plusses(n, cap):\n    \"\"\"Count plus expressions for n whose value is < cap.\n    >>> plusses(123, 16)   # 1+2+3=6 and 12+3=15 count; 1+23=24 does not\n    2\n    >>> plusses(2018, 38)\n    4\n    >>> plusses(1, 2)\n    1\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def plusses(n, cap):\n    s = str(n)\n    def go(s, acc):\n        if s == \"\":\n            return 1 if acc < cap else 0\n        total = go(s[1:], acc + int(s[0]))\n        if len(s) >= 2:\n            total += go(s[2:], acc + int(s[:2]))\n        return total\n    return go(s, 0)",
  "tests": "assert plusses(123, 16) == 2\nassert plusses(2018, 38) == 4\nassert plusses(1, 2) == 1\nassert plusses(9, 5) == 0"
 },
 {
  "id": "fa17_ways",
  "title": "Both Ways (counting paths)",
  "cat": "Recursion",
  "source": "Fall 2017 MT2, Q4(c)",
  "exam": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2_sol.pdf",
  "desc": "Count sequences of at most k functions from actions (repeats allowed) that, applied in order to start, produce end. Once end is reached the path stops and counts as one way.",
  "setup": "",
  "starter": "def ways(start, end, k, actions):\n    \"\"\"Count length-<=k action sequences taking start to end.\n    >>> ways(-1, 1, 5, [abs, lambda x: x + 2])\n    2\n    >>> ways(1, 10, 5, [lambda x: x + 1, lambda x: x + 4])\n    3\n    >>> ways(1, 20, 5, [lambda x: x + 1, lambda x: x + 4])\n    0\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def ways(start, end, k, actions):\n    if start == end:\n        return 1\n    if k == 0:\n        return 0\n    return sum(ways(f(start), end, k - 1, actions) for f in actions)",
  "tests": "assert ways(-1, 1, 5, [abs, lambda x: x + 2]) == 2\nassert ways(1, 10, 5, [lambda x: x + 1, lambda x: x + 4]) == 3\nassert ways(1, 20, 5, [lambda x: x + 1, lambda x: x + 4]) == 0\nassert ways(5, 5, 0, [lambda x: x + 1]) == 1"
 },
 {
  "id": "fa14_no_eleven",
  "title": "This One Goes to Eleven (no_eleven)",
  "cat": "Recursion",
  "source": "Fall 2014 MT2, Q3(b)",
  "exam": "https://cs61a.org/resources/fa14/mt2/61a-fa14-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa14/mt2/61a-fa14-mt2_sol.pdf",
  "desc": "Return all length-n lists of 1s and 6s in which no 1 is directly followed by another 1. Order must match the doctests.",
  "setup": "",
  "starter": "def no_eleven(n):\n    \"\"\"All length-n lists of 1s and 6s with no two adjacent 1s.\n    >>> no_eleven(2)\n    [[6, 6], [6, 1], [1, 6]]\n    >>> no_eleven(3)\n    [[6, 6, 6], [6, 6, 1], [6, 1, 6], [1, 6, 6], [1, 6, 1]]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def no_eleven(n):\n    if n == 0:\n        return [[]]\n    if n == 1:\n        return [[6], [1]]\n    return ([[6] + r for r in no_eleven(n - 1)] +\n            [[1, 6] + r for r in no_eleven(n - 2)])",
  "tests": "assert no_eleven(2) == [[6, 6], [6, 1], [1, 6]]\nassert no_eleven(3) == [[6, 6, 6], [6, 6, 1], [6, 1, 6], [1, 6, 6], [1, 6, 1]]\nassert no_eleven(1) == [[6], [1]]"
 },
 {
  "id": "fa25_exclude",
  "title": "Exclusive (list)",
  "cat": "Lists & Dicts",
  "source": "Fall 2025 MT2, Q4(a)",
  "exam": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2_sol.pdf",
  "desc": "Return a new list of the elements of s that are not equal to x. Do not change s.",
  "setup": "",
  "starter": "def exclude(s, x):\n    \"\"\"Return a new list of elements of s not equal to x.\n    >>> exclude([1, 2, 3, 2, 1], 2)\n    [1, 3, 1]\n    >>> exclude([], 5)\n    []\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def exclude(s, x):\n    return [e for e in s if e != x]",
  "tests": "assert exclude([1, 2, 3, 2, 1], 2) == [1, 3, 1]\nassert exclude([], 5) == []\nassert exclude([7, 7, 7], 7) == []\n_a = [1, 2, 3]\nexclude(_a, 2)\nassert _a == [1, 2, 3]  # input unchanged"
 },
 {
  "id": "fa25_symmetrical",
  "title": "Two Topping Pizzas (symmetrical)",
  "cat": "Lists & Dicts",
  "source": "Fall 2025 MT2, Q6(a)",
  "exam": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2_sol.pdf",
  "desc": "Return whether every key-value pair in dict d also appears reversed: for every key k with value v, d[v] exists and equals k.",
  "setup": "",
  "starter": "def symmetrical(d):\n    \"\"\"Return whether d maps symmetrically.\n    >>> symmetrical({'M': 'P', 'P': 'M'})\n    True\n    >>> symmetrical({'M': 'P'})\n    False\n    >>> symmetrical({})\n    True\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def symmetrical(d):\n    return all([d.get(v) == k for k, v in d.items()])",
  "tests": "assert symmetrical({'M': 'P', 'P': 'M'}) is True\nassert symmetrical({'M': 'P'}) is False\nassert symmetrical({}) is True\nassert symmetrical({'a': 'a'}) is True"
 },
 {
  "id": "fa25_acceptable",
  "title": "Two Topping Pizzas (acceptable)",
  "cat": "Lists & Dicts",
  "source": "Fall 2025 MT2, Q6(b)",
  "exam": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2_sol.pdf",
  "desc": "A pizza is a string of toppings. disallow is a symmetrical dict of pairs that may not sit next to each other. Return whether no two adjacent slices (the first and last count as adjacent) form a disallowed pair.",
  "setup": "def symmetrical(d):\n    return all([d.get(v) == k for k, v in d.items()])",
  "starter": "def acceptable(pizza, disallow):\n    \"\"\"Return whether no adjacent slices form a disallowed pair (wrapping around).\n    >>> no_mp = {'M': 'P', 'P': 'M'}\n    >>> acceptable('MM_P', no_mp)   # last P wraps next to first M\n    False\n    >>> acceptable('M_P_', no_mp)\n    True\n    >>> acceptable('MPM', no_mp)\n    False\n    \"\"\"\n    assert symmetrical(disallow)\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def acceptable(pizza, disallow):\n    assert symmetrical(disallow)\n    n = len(pizza)\n    for i in range(n):\n        a, b = pizza[i], pizza[(i + 1) % n]\n        if disallow.get(a) == b:\n            return False\n    return True",
  "tests": "no_mp = {'M': 'P', 'P': 'M'}\nassert acceptable('MM_P', no_mp) is False\nassert acceptable('M_P_', no_mp) is True\nassert acceptable('MPM', no_mp) is False\nassert acceptable('____', no_mp) is True"
 },
 {
  "id": "sp24_is_strip",
  "title": "Who's counting? (is_strip)",
  "cat": "Lists & Dicts",
  "source": "Spring 2024 MT2, Q4(a)",
  "exam": "https://cs61a.org/resources/sp24/mt2/61a-sp24-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp24/mt2/61a-sp24-mt2_sol.pdf",
  "desc": "Return whether each element of list s is exactly one more than the element before it. Empty and one-element lists count as strips.",
  "setup": "",
  "starter": "def is_strip(s):\n    \"\"\"Return whether s is a run of consecutive increasing integers.\n    >>> is_strip([3, 4, 5, 6])\n    True\n    >>> is_strip([3, 3, 3])\n    False\n    >>> is_strip([5])\n    True\n    \"\"\"\n    assert type(s) == list\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def is_strip(s):\n    assert type(s) == list\n    return s == [] or s == list(range(s[0], s[0] + len(s)))",
  "tests": "assert is_strip([3, 4, 5, 6]) is True\nassert is_strip([3, 3, 3]) is False\nassert is_strip([5]) is True\nassert is_strip([]) is True\nassert is_strip([4, 5, 7]) is False"
 },
 {
  "id": "sp24_drip",
  "title": "Who's counting? (drip)",
  "cat": "Lists & Dicts",
  "source": "Spring 2024 MT2, Q4(b)",
  "exam": "https://cs61a.org/resources/sp24/mt2/61a-sp24-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp24/mt2/61a-sp24-mt2_sol.pdf",
  "desc": "s and t are non-empty lists. Return whether a single strip starting at s[0] uses all and only the elements of s and t, keeping each list's elements in their original order.",
  "setup": "def is_strip(s):\n    assert type(s) == list\n    return s == [] or s == list(range(s[0], s[0] + len(s)))",
  "starter": "def drip(s, t):\n    \"\"\"Return whether s and t interleave into one consecutive strip from s[0].\n    >>> drip([1, 3, 5], [2, 4, 6])   # 1 2 3 4 5 6\n    True\n    >>> drip([2, 4, 5], [1, 3, 6])\n    False\n    >>> drip([1], [2, 3, 5])         # would need a 4\n    False\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def drip(s, t):\n    i = j = 0\n    expected = s[0]\n    while i < len(s) or j < len(t):\n        if i < len(s) and s[i] == expected:\n            i += 1\n        elif j < len(t) and t[j] == expected:\n            j += 1\n        else:\n            return False\n        expected += 1\n    return True",
  "tests": "assert drip([1, 3, 5], [2, 4, 6]) is True\nassert drip([2, 4, 5], [1, 3, 6]) is False\nassert drip([1], [2, 3, 5]) is False\nassert drip([1, 2, 3], [4, 5, 6]) is True"
 },
 {
  "id": "sp23_prefix",
  "title": "Prefixes (list)",
  "cat": "Lists & Dicts",
  "source": "Spring 2023 MT2, Q3(a)",
  "exam": "https://cs61a.org/resources/sp23/mt2/61a-sp23-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp23/mt2/61a-sp23-mt2_sol.pdf",
  "desc": "Return the list of prefix sums of s (the sum of the first i elements, for each i from 1 to len(s)), ordered by increasing prefix length.",
  "setup": "",
  "starter": "def prefix(s):\n    \"\"\"Return the prefix sums of s.\n    >>> prefix([1, 2, 3, 0, 4, 5])\n    [1, 3, 6, 6, 10, 15]\n    >>> prefix([2, 2, 2, 0, -5, 5])\n    [2, 4, 6, 6, 1, 6]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def prefix(s):\n    return [sum(s[:i + 1]) for i in range(len(s))]",
  "tests": "assert prefix([1, 2, 3, 0, 4, 5]) == [1, 3, 6, 6, 10, 15]\nassert prefix([2, 2, 2, 0, -5, 5]) == [2, 4, 6, 6, 1, 6]\nassert prefix([7]) == [7]\nassert prefix([]) == []"
 },
 {
  "id": "fa21_amounts",
  "title": "Doctor Change",
  "cat": "Lists & Dicts",
  "source": "Fall 2021 MT2, Q2(b)",
  "exam": "https://cs61a.org/resources/fa21/mt2/61a-fa21-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa21/mt2/61a-fa21-mt2_sol.pdf",
  "desc": "Return a sorted list of the unique non-negative integers reachable as a sum of a subset of coins, including 0.",
  "setup": "",
  "starter": "def amounts(coins):\n    \"\"\"Sorted unique subset sums of coins, including 0.\n    >>> amounts([4])\n    [0, 4]\n    >>> amounts([])\n    [0]\n    >>> amounts([2, 2])\n    [0, 2, 4]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def amounts(coins):\n    if len(coins) == 0:\n        return [0]\n    rest = amounts(coins[1:])\n    return sorted(set(rest + [coins[0] + r for r in rest]))",
  "tests": "assert amounts([4]) == [0, 4]\nassert amounts([]) == [0]\nassert amounts([2, 2]) == [0, 2, 4]\nassert amounts([1, 2, 4]) == [0, 1, 2, 3, 4, 5, 6, 7]"
 },
 {
  "id": "fa21_max_diff",
  "title": "Thanos (max_diff_fast)",
  "cat": "Lists & Dicts",
  "source": "Fall 2021 MT2, Q4(b)-(c)",
  "exam": "https://cs61a.org/resources/fa21/mt2/61a-fa21-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa21/mt2/61a-fa21-mt2_sol.pdf",
  "desc": "Given a non-empty sequence s and a one-argument function f, return the pair (v, w) of elements of s that maximizes f(v) - f(w). Use max and min with a key (no nested loops).",
  "setup": "",
  "starter": "def max_diff_fast(s, f):\n    \"\"\"Return (v, w) from s maximizing f(v) - f(w).\n    >>> max_diff_fast(range(-7, 4), lambda x: x * x)\n    (-7, 0)\n    >>> max_diff_fast(['what', 'a', 'great', 'film'], len)\n    ('great', 'a')\n    >>> max_diff_fast([1, 2, 3], lambda x: x)\n    (3, 1)\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def max_diff_fast(s, f):\n    s = list(s)\n    return (max(s, key=f), min(s, key=f))",
  "tests": "assert max_diff_fast(range(-7, 4), lambda x: x * x) == (-7, 0)\nassert max_diff_fast(['what', 'a', 'great', 'film'], len) == ('great', 'a')\nassert max_diff_fast([1, 2, 3], lambda x: x) == (3, 1)"
 },
 {
  "id": "fa19_stable",
  "title": "Seek Once",
  "cat": "Lists & Dicts",
  "source": "Fall 2019 MT2, Q4",
  "exam": "https://cs61a.org/resources/fa19/mt2/61a-fa19-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa19/mt2/61a-fa19-mt2_sol.pdf",
  "desc": "Return whether every pair of elements of list s whose indices differ by at most k has values differing by at most n.",
  "setup": "",
  "starter": "def stable(s, k, n):\n    \"\"\"Return whether nearby elements stay close in value.\n    >>> stable([1, 2, 3, 5, 6], 1, 2)\n    True\n    >>> stable([1, 2, 3, 5, 6], 2, 2)\n    False\n    >>> stable([1, 5, 1, 5, 1], 2, 2)\n    False\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def stable(s, k, n):\n    return all(abs(s[i] - s[j]) <= n\n               for i in range(len(s))\n               for j in range(max(0, i - k), i))",
  "tests": "assert stable([1, 2, 3, 5, 6], 1, 2) is True\nassert stable([1, 2, 3, 5, 6], 2, 2) is False\nassert stable([1, 5, 1, 5, 1], 2, 2) is False\nassert stable([10], 3, 0) is True"
 },
 {
  "id": "fa18_lowest",
  "title": "Lowest",
  "cat": "Lists & Dicts",
  "source": "Fall 2018 MT2, Q2",
  "exam": "https://cs61a.org/resources/fa18/mt2/61a-fa18-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa18/mt2/61a-fa18-mt2_sol.pdf",
  "desc": "Return a list of the elements of s whose absolute value equals the smallest absolute value in s, in original order, duplicates kept.",
  "setup": "",
  "starter": "def lowest(s):\n    \"\"\"Elements of s tied for smallest absolute value.\n    >>> lowest([3, -2, 2, -3, -4, 2, 3, 4])\n    [-2, 2, 2]\n    >>> lowest(range(-5, 5))\n    [0]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def lowest(s):\n    s = list(s)\n    m = abs(min(s, key=abs))\n    return [x for x in s if abs(x) == m]",
  "tests": "assert lowest([3, -2, 2, -3, -4, 2, 3, 4]) == [-2, 2, 2]\nassert lowest(list(range(-5, 5))) == [0]\nassert lowest([-1, 1, -3]) == [-1, 1]"
 },
 {
  "id": "fa17_splice",
  "title": "Pumpkin Splice Latte (splice)",
  "cat": "Lists & Dicts",
  "source": "Fall 2017 MT2, Q3(a)",
  "exam": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2_sol.pdf",
  "desc": "Return a new list made of a[:k], then all of b, then a[k:]. Do not modify a or b.",
  "setup": "",
  "starter": "def splice(a, b, k):\n    \"\"\"Insert all of b into a at index k.\n    >>> splice([2, 3, 4, 5], [6, 7], 2)\n    [2, 3, 6, 7, 4, 5]\n    >>> splice([1, 2], [], 0)\n    [1, 2]\n    >>> splice([1], [5, 6], 0)\n    [5, 6, 1]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def splice(a, b, k):\n    return a[:k] + list(b) + a[k:]",
  "tests": "assert splice([2, 3, 4, 5], [6, 7], 2) == [2, 3, 6, 7, 4, 5]\nassert splice([1, 2], [], 0) == [1, 2]\nassert splice([1], [5, 6], 0) == [5, 6, 1]\nassert splice([1, 2], [9], 2) == [1, 2, 9]"
 },
 {
  "id": "fa17_all_splice",
  "title": "Pumpkin Splice Latte (all_splice)",
  "cat": "Lists & Dicts",
  "source": "Fall 2017 MT2, Q3(b)",
  "exam": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2_sol.pdf",
  "desc": "Return the increasing list of every index k from 0 to len(a) where splice(a, b, k) equals c. You may assume splice is correct.",
  "setup": "def splice(a, b, k):\n    return a[:k] + list(b) + a[k:]",
  "starter": "def all_splice(a, b, c):\n    \"\"\"All k where splicing b into a at k gives c.\n    >>> all_splice([1, 2], [3, 4], [1, 3, 4, 2])\n    [1]\n    >>> all_splice([1, 2, 1, 2], [1, 2], [1, 2, 1, 2, 1, 2])\n    [0, 2, 4]\n    >>> all_splice([1], [2], [3])\n    []\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def all_splice(a, b, c):\n    return [k for k in range(len(a) + 1) if splice(a, b, k) == c]",
  "tests": "assert all_splice([1, 2], [3, 4], [1, 3, 4, 2]) == [1]\nassert all_splice([1, 2, 1, 2], [1, 2], [1, 2, 1, 2, 1, 2]) == [0, 2, 4]\nassert all_splice([1], [2], [3]) == []"
 },
 {
  "id": "fa15_int_set",
  "title": "Return of the Digits (challenge)",
  "cat": "Lists & Dicts",
  "source": "Fall 2015 MT2, Q3(e)",
  "exam": "https://cs61a.org/resources/fa15/mt2/61a-fa15-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa15/mt2/61a-fa15-mt2_sol.pdf",
  "desc": "CHALLENGE. bits(nums) is provided: calling it with 0 or 1 descends one binary level keeping numbers whose lowest bit matches (that bit removed); calling it with 'entry' returns whether 0 is present. Build int_set(contents) returning a function contains(n) that reports membership, descending n's binary digits from least significant. You may not use `in` or list.index in your own code.",
  "setup": "def bits(nums):\n    def branch(b):\n        if b == 'entry':\n            return 0 in nums\n        return bits([k >> 1 for k in nums if k & 1 == b])\n    return branch",
  "starter": "def int_set(contents):\n    \"\"\"Return a membership function for the integers in contents.\n    >>> int_set([1, 2])(1)\n    True\n    >>> int_set([1, 2])(3)\n    False\n    >>> s = int_set([1, 3, 4, 7, 9])\n    >>> [s(k) for k in range(10)]\n    [False, True, False, True, True, False, False, True, False, True]\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def int_set(contents):\n    def contains(n):\n        index = bits(contents)\n        while n > 0:\n            index = index(n & 1)\n            n = n >> 1\n        return index('entry')\n    return contains",
  "tests": "assert int_set([1, 2])(1) is True\nassert int_set([1, 2])(3) is False\ns = int_set([1, 3, 4, 7, 9])\nassert [s(k) for k in range(10)] == [False, True, False, True, True, False, False, True, False, True]"
 },
 {
  "id": "fa25_exclude_link",
  "title": "Exclusive (linked list)",
  "cat": "Linked Lists",
  "source": "Fall 2025 MT2, Q4(b)",
  "exam": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa25/mt2/61a-fa25-mt2_sol.pdf",
  "desc": "Return a new linked list of the elements of linked list s that are not equal to x. Do not change s. (Empty is ().)",
  "setup": "",
  "starter": "def exclude_link(s, x):\n    \"\"\"Return a new Link of the elements of s not equal to x.\n    >>> exclude_link(Link(1, Link(2, Link(3, Link(2)))), 2)\n    Link(1, Link(3))\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def exclude_link(s, x):\n    if not isinstance(s, Link):\n        return ()\n    if s.first == x:\n        return exclude_link(s.rest, x)\n    return Link(s.first, exclude_link(s.rest, x))",
  "tests": "assert to_list(exclude_link(make_link([1, 2, 3, 2]), 2)) == [1, 3]\nassert to_list(exclude_link(make_link([]), 2)) == []\nassert to_list(exclude_link(make_link([2, 2, 2]), 2)) == []\n_s = make_link([1, 2, 3])\nexclude_link(_s, 2)\nassert to_list(_s) == [1, 2, 3]  # input unchanged"
 },
 {
  "id": "sp25_muladd",
  "title": "Just Add and Multiply (muladd)",
  "cat": "Linked Lists",
  "source": "Spring 2025 MT2, Q5(a)",
  "exam": "https://cs61a.org/resources/sp25/mt2/61a-sp25-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp25/mt2/61a-sp25-mt2_sol.pdf",
  "desc": "s is a linked list of numbers. Evaluate the expression that alternates *, +, *, + ... starting with * between the first pair. With normal precedence this multiplies each consecutive pair and sums the products. A single element returns itself; empty returns 0.",
  "setup": "",
  "starter": "def muladd(s):\n    \"\"\"Evaluate the alternating * + * ... expression over s.\n    >>> muladd(Link(9, Link(4, Link(7, Link(2, Link(0))))))  # 9*4 + 7*2 + 0\n    50\n    >>> muladd(Link(2, Link(9, Link(4, Link(7, Link(2, Link(0)))))))  # 2*9 + 4*7 + 2*0\n    46\n    >>> muladd(Link(2))\n    2\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def muladd(s):\n    if not isinstance(s, Link):\n        return 0\n    if not isinstance(s.rest, Link):\n        return s.first\n    return s.first * s.rest.first + muladd(s.rest.rest)",
  "tests": "assert muladd(make_link([9, 4, 7, 2, 0])) == 50\nassert muladd(make_link([2, 9, 4, 7, 2, 0])) == 46\nassert muladd(make_link([2])) == 2\nassert muladd(()) == 0"
 },
 {
  "id": "fa24_longest",
  "title": "How Long is this Exam?",
  "cat": "Linked Lists",
  "source": "Fall 2024 MT2, Q5",
  "exam": "https://cs61a.org/resources/fa24/mt2/61a-fa24-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa24/mt2/61a-fa24-mt2_sol.pdf",
  "desc": "s is a linked list of positive integers, n a positive integer. Return a longest sublist (subsequence, order kept) of s whose elements sum to at most n. Ties may return any longest one. Do not mutate s. The helper longer(s, t) (returns the longer list, or s if equal) is provided.",
  "setup": "def _len(x):\n    n = 0\n    while isinstance(x, Link):\n        n += 1\n        x = x.rest\n    return n\ndef longer(s, t):\n    return s if _len(s) >= _len(t) else t",
  "starter": "def longest(s, n):\n    \"\"\"Return a longest sublist of s that sums to at most n.\n    longer(s, t) is provided: it returns whichever list is longer (s if tied).\n    >>> longest(Link(5, Link(1, Link(3, Link(4, Link(2, Link(7)))))), 7)\n    Link(1, Link(3, Link(2)))\n    >>> longest(Link(3, Link(4, Link(5))), 2)\n    ()\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def longest(s, n):\n    if not isinstance(s, Link):\n        return ()\n    without = longest(s.rest, n)\n    if s.first <= n:\n        with_it = Link(s.first, longest(s.rest, n - s.first))\n        return longer(with_it, without)\n    return without",
  "tests": "r = longest(make_link([5, 1, 3, 4, 2, 7]), 7)\nassert sum(to_list(r)) <= 7 and len(to_list(r)) == 3\nfull = longest(make_link([5, 1, 3, 4, 2, 7]), 70)\nassert to_list(full) == [5, 1, 3, 4, 2, 7]\nassert to_list(longest(make_link([3, 4, 5]), 2)) == []"
 },
 {
  "id": "fa23_after",
  "title": "After Party",
  "cat": "Linked Lists",
  "source": "Fall 2023 MT2, Q6(a)-(b)",
  "exam": "https://cs61a.org/resources/fa23/mt2/61a-fa23-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa23/mt2/61a-fa23-mt2_sol.pdf",
  "desc": "s is a linked list. Return whether some element equal to b appears strictly after some element equal to a.",
  "setup": "",
  "starter": "def after(s, a, b):\n    \"\"\"Return whether a b appears after an a in s.\n    >>> t = Link(3, Link(6, Link(5, Link(4))))\n    >>> after(t, 6, 4)\n    True\n    >>> after(t, 4, 6)\n    False\n    >>> after(t, 6, 6)\n    False\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def after(s, a, b):\n    found = False\n    while isinstance(s, Link):\n        if found and s.first == b:\n            return True\n        if s.first == a:\n            found = True\n        s = s.rest\n    return False",
  "tests": "t = make_link([3, 6, 5, 4])\nassert after(t, 6, 4) is True\nassert after(t, 4, 6) is False\nassert after(t, 6, 6) is False\nassert after(make_link([1, 2, 1, 2]), 1, 2) is True"
 },
 {
  "id": "sp23_tens",
  "title": "Prefixes (linked list)",
  "cat": "Linked Lists",
  "source": "Spring 2023 MT2, Q3(b)",
  "exam": "https://cs61a.org/resources/sp23/mt2/61a-sp23-mt2.pdf",
  "sol": "https://cs61a.org/resources/sp23/mt2/61a-sp23-mt2_sol.pdf",
  "desc": "s is a non-empty linked list of numbers. Print each prefix sum that is a multiple of 10, in order of increasing prefix length. Returns nothing.",
  "setup": "",
  "starter": "def tens(s):\n    \"\"\"Print the prefix sums of s that are multiples of 10.\n    >>> tens(Link(3, Link(9, Link(8, Link(10, Link(0, Link(14, Link(6))))))))\n    20\n    30\n    30\n    50\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def tens(s):\n    def f(suffix, total):\n        if not isinstance(suffix, Link):\n            return\n        total += suffix.first\n        if total % 10 == 0:\n            print(total)\n        f(suffix.rest, total)\n    f(s, 0)",
  "tests": "out = _caught_out(lambda: tens(make_link([3, 9, 8, 10, 0, 14, 6])))\nassert out == \"20\\n30\\n30\\n50\\n\"\nout2 = _caught_out(lambda: tens(make_link([1, 2])))\nassert out2 == \"\"\nout3 = _caught_out(lambda: tens(make_link([10])))\nassert out3 == \"10\\n\""
 },
 {
  "id": "fa20_filter_index",
  "title": "Filtering by index",
  "cat": "Linked Lists",
  "source": "Fall 2020 MT2, Q2(b)",
  "exam": "https://cs61a.org/resources/fa20/mt2/61a-fa20-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa20/mt2/61a-fa20-mt2_sol.pdf",
  "desc": "f is a one-argument function applied to indices (0-based), s is a linked list. Return a new linked list of the elements whose index i makes f(i) true, order kept.",
  "setup": "",
  "starter": "def filter_index(f, s):\n    \"\"\"Keep elements of s whose index satisfies f.\n    >>> powers = Link(1, Link(2, Link(4, Link(8, Link(16, Link(32))))))\n    >>> filter_index(lambda i: i < 4, powers)\n    Link(1, Link(2, Link(4, Link(8))))\n    >>> filter_index(lambda i: i % 2 == 1, powers)\n    Link(2, Link(8, Link(32)))\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def filter_index(f, s):\n    def go(s, i):\n        if not isinstance(s, Link):\n            return ()\n        if f(i):\n            return Link(s.first, go(s.rest, i + 1))\n        return go(s.rest, i + 1)\n    return go(s, 0)",
  "tests": "powers = make_link([1, 2, 4, 8, 16, 32])\nassert to_list(filter_index(lambda i: i < 4, powers)) == [1, 2, 4, 8]\nassert to_list(filter_index(lambda i: i % 2 == 1, powers)) == [2, 8, 32]\nassert to_list(filter_index(lambda i: False, powers)) == []"
 },
 {
  "id": "fa17_splink",
  "title": "Pumpkin Splice Latte (splink)",
  "cat": "Linked Lists",
  "source": "Fall 2017 MT2, Q3(c)",
  "exam": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2_sol.pdf",
  "desc": "a and b are linked lists. Return a new linked list with the first k elements of a, then all of b, then the rest of a. No len, indexing, slicing, or list conversion; use recursion.",
  "setup": "",
  "starter": "def splink(a, b, k):\n    \"\"\"Splice linked list b into a at position k.\n    >>> splink(Link(2, Link(3, Link(4))), Link(6, Link(7)), 2)\n    Link(2, Link(3, Link(6, Link(7, Link(4)))))\n    >>> splink(Link(1), Link(2), 0)\n    Link(2, Link(1))\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def splink(a, b, k):\n    if not isinstance(b, Link):\n        return a\n    if k == 0:\n        return Link(b.first, splink(a, b.rest, 0))\n    return Link(a.first, splink(a.rest, b, k - 1))",
  "tests": "assert to_list(splink(make_link([2, 3, 4]), make_link([6, 7]), 2)) == [2, 3, 6, 7, 4]\nassert to_list(splink(make_link([1, 2]), (), 1)) == [1, 2]\nassert to_list(splink(make_link([1]), make_link([2]), 0)) == [2, 1]"
 },
 {
  "id": "fa17_both",
  "title": "Both Ways (both)",
  "cat": "Linked Lists",
  "source": "Fall 2017 MT2, Q4(a)",
  "exam": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa17/mt2/61a-fa17-mt2_sol.pdf",
  "desc": "a and b are sorted (increasing) linked lists. Return whether they share at least one value. Use recursion.",
  "setup": "",
  "starter": "def both(a, b):\n    \"\"\"Return whether sorted linked lists a and b share a value.\n    >>> both(Link(1, Link(3, Link(5, Link(7)))), Link(2, Link(4, Link(6))))\n    False\n    >>> both(Link(1, Link(3, Link(5, Link(7)))), Link(2, Link(7, Link(9))))\n    True\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def both(a, b):\n    if not isinstance(a, Link) or not isinstance(b, Link):\n        return False\n    if a.first > b.first:\n        a, b = b, a\n    if a.first == b.first:\n        return True\n    return both(a.rest, b)",
  "tests": "assert both(make_link([1, 3, 5, 7]), make_link([2, 4, 6])) is False\nassert both(make_link([1, 3, 5, 7]), make_link([2, 7, 9])) is True\nassert both((), make_link([2])) is False\nassert both(make_link([4]), make_link([4])) is True"
 },
 {
  "id": "fa14_sixty_ones",
  "title": "This One Goes to Eleven (sixty_ones)",
  "cat": "Linked Lists",
  "source": "Fall 2014 MT2, Q3(a)",
  "exam": "https://cs61a.org/resources/fa14/mt2/61a-fa14-mt2.pdf",
  "sol": "https://cs61a.org/resources/fa14/mt2/61a-fa14-mt2_sol.pdf",
  "desc": "s is a linked list of integers. Count the positions where a 1 immediately follows a 6.",
  "setup": "",
  "starter": "def sixty_ones(s):\n    \"\"\"Count the number of times 1 directly follows 6 in s.\n    >>> sixty_ones(Link(6, Link(1)))\n    1\n    >>> sixty_ones(Link(6, Link(1, Link(6, Link(1)))))\n    2\n    >>> sixty_ones(Link(1, Link(6, Link(6, Link(1)))))\n    1\n    \"\"\"\n    \"*** YOUR CODE HERE ***\"",
  "solution": "def sixty_ones(s):\n    if not isinstance(s, Link) or not isinstance(s.rest, Link):\n        return 0\n    extra = 1 if s.first == 6 and s.rest.first == 1 else 0\n    return extra + sixty_ones(s.rest)",
  "tests": "assert sixty_ones(()) == 0\nassert sixty_ones(make_link([6, 1])) == 1\nassert sixty_ones(make_link([6, 1, 6, 1])) == 2\nassert sixty_ones(make_link([1, 6, 6, 1])) == 1"
 }
];
